repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/kamadorueda/alejandra
    rev: 4.0.0
    hooks:
      # Requires Alejandra to be previously installed in the system
      - id: alejandra-system
